module.exports = {
  ROOM_STATE_WAITING: "ROOM_STATE_WAITING",
  ROOM_STATE_ROUND_DEAL: "ROOM_STATE_ROUND_DEAL",
  ROOM_STATE_ROUND_FLOP: "ROOM_STATE_ROUND_FLOP",
  ROOM_STATE_ROUND_TURN: "ROOM_STATE_ROUND_TURN",
  ROOM_STATE_ROUND_RIVER: "ROOM_STATE_ROUND_RIVER",
  ROOM_STATE_ROUND_SHOWDOWN: "ROOM_STATE_ROUND_SHOWDOWN",
};
